trigger:
- master

continueOnError: true

pool: LocalPool
#pool:
  #vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'GraduateWork\GraduateWork.csproj'

- task: PublishAllureReport@1
  condition: always()
  displayName: Publish Report
  inputs:
    allureVersion: 2.27.0
    testResultsDir: GraduateWork\bin\Debug\net8.0\allure-results

- task: PublishPipelineArtifact@1
  condition: always()
  displayName: Publish Artifact
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'